(cl:defpackage ged-msg
  (:use )
  (:export
   "<GOTOPOINTPOLARACTION>"
   "GOTOPOINTPOLARACTION"
   "<GOTOPOINTPOLARACTIONFEEDBACK>"
   "GOTOPOINTPOLARACTIONFEEDBACK"
   "<GOTOPOINTPOLARACTIONGOAL>"
   "GOTOPOINTPOLARACTIONGOAL"
   "<GOTOPOINTPOLARACTIONRESULT>"
   "GOTOPOINTPOLARACTIONRESULT"
   "<GOTOPOINTPOLARFEEDBACK>"
   "GOTOPOINTPOLARFEEDBACK"
   "<GOTOPOINTPOLARGOAL>"
   "GOTOPOINTPOLARGOAL"
   "<GOTOPOINTPOLARRESULT>"
   "GOTOPOINTPOLARRESULT"
  ))

